
<div id="carbonads">
<span>
<span class="carbon-wrap">
<a href="https://github.com/booboowei" class="carbon-img" target="_blank" rel="noopener sponsored">
    <img src="https://avatars2.githubusercontent.com/u/21328020?s=460&u=88cf6127c32932188f936d05636b7b0d36783ee1&v=4"
    alt="ads via Carbon" border="0" style="max-width: 130px;">
</a>
<a href="https://scientistcafe.com/" class="carbon-text" target="_blank" rel="noopener sponsored">除了自己的无知，我什么都不知道</a>
</span>
</span>
